# -*- coding: utf-8 -*-
"""Copy of Copy of CV_YoloV4_Train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-0orcCzaEB-4RrbhiNe6iy6ks-YNNOc
"""

# Commented out IPython magic to ensure Python compatibility.
!sudo echo -ne '\n' | sudo add-apt-repository ppa:alessandro-strada/ppa >/dev/null 2>&1 # note: >/dev/null 2>&1 is used to supress printing
!sudo apt update >/dev/null 2>&1
!sudo apt install google-drive-ocamlfuse >/dev/null 2>&1
!google-drive-ocamlfuse
!sudo apt-get install w3m >/dev/null 2>&1 # to act as web browser 
!xdg-settings set default-web-browser w3m.desktop >/dev/null 2>&1 # to set default browser 
# %cd /content
!mkdir gdrive
# %cd gdrive
!mkdir "MyDrive"
!google-drive-ocamlfuse "/content/gdrive/MyDrive"

import os
os.chdir('/content/gdrive/MyDrive')

!git clone https://github.com/ultralytics/yolov5  # clone

import os
os.chdir('/content/gdrive/MyDrive/yolov5')

!pip install -r requirements.txt  # install

!python train.py --data VisDrone.yaml --epochs 30 --weights '' --cfg yolov5l.yaml  --batch-size 24

